connect 'localhost:/srv/db/ping.db' user 'SYSDBA' password 'ping';

create ping_hourly (
id int generated by default as identity primary key,
ts timestamp,
avg_respone decimal(4,8),
count int
);

create ping_daily (
id int generated by default as identity primary key,
ts timestamp,
avg_respone decimal(4,8)
);

create table log (
id int generated by default as identity primary key,
ts timestamp default current_timestamp,
text varchar(8000)
);

